// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	ID        string  `json:"id"`
	Firstname string  `json:"firstname"`
	Lastname  string  `json:"lastname"`
	Phone     string  `json:"phone"`
	Email     *string `json:"email"`
	Country   string  `json:"country"`
}

type CustomerInput struct {
	Firstname string  `json:"firstname"`
	Lastname  string  `json:"lastname"`
	Phone     string  `json:"phone"`
	Email     *string `json:"email"`
	Country   string  `json:"country"`
}

type Transaction struct {
	ID                 string              `json:"id"`
	Txcode             string              `json:"txcode"`
	Sender             *Customer           `json:"sender"`
	Receiver           *Customer           `json:"receiver"`
	TransactionDetails *TransactionDetails `json:"transactionDetails"`
	SenderAgentID      *string             `json:"senderAgentID"`
	ReceiverAgentID    *string             `json:"receiverAgentID"`
	Status             string              `json:"status"`
}

type TransactionDetails struct {
	ID               string  `json:"id"`
	Txcode           string  `json:"txcode"`
	SentAmount       float64 `json:"sentAmount"`
	SentCurrency     string  `json:"sentCurrency"`
	ReceivedAmount   float64 `json:"receivedAmount"`
	ReceivedCurrency string  `json:"receivedCurrency"`
	Xchange          float64 `json:"xchange"`
	Fees             float64 `json:"fees"`
	PaymentMode      string  `json:"paymentMode"`
	ReceptionMode    string  `json:"receptionMode"`
}

type TransactionDetailsInput struct {
	Txcode           string  `json:"txcode"`
	SentAmount       float64 `json:"sentAmount"`
	SentCurrency     string  `json:"sentCurrency"`
	ReceivedAmount   float64 `json:"receivedAmount"`
	ReceivedCurrency string  `json:"receivedCurrency"`
	Xchange          float64 `json:"xchange"`
	Fees             float64 `json:"fees"`
	PaymentMode      string  `json:"paymentMode"`
	ReceptionMode    string  `json:"receptionMode"`
}

type TransactionInput struct {
	Txcode             string                   `json:"txcode"`
	Sender             *CustomerInput           `json:"sender"`
	Receiver           *CustomerInput           `json:"receiver"`
	TransactionDetails *TransactionDetailsInput `json:"transactionDetails"`
	SenderAgentID      *string                  `json:"senderAgentID"`
	ReceiverAgentID    *string                  `json:"receiverAgentID"`
	Status             string                   `json:"status"`
}
