// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/jinzhu/gorm"
)
type Customer struct {
	gorm.Model
	Firstname   string         `json:"firstname"`
	Lastname    string         `json:"lastname"`
	Phone       string         `json:"phone"`
	Email       *string        `json:"email"`
	Country     string         `json:"country"`
	Receptions  []*Transaction `json:"receptions"`
	Expiditions []*Transaction `json:"expiditions"`
}

type CustomerChanges struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

type CustomerInput struct {
	Firstname string  `json:"firstname"`
	Lastname  string  `json:"lastname"`
	Phone     string  `json:"phone"`
	Email     *string `json:"email"`
	Country   string  `json:"country"`
}

type ReceptionInput struct {
	ReceiverAgentID *string `json:"receiverAgentID"`
	Status          string  `json:"status"`
}

type Transaction struct {
	gorm.Model
	SenderID           uint               `json:"senderID"`
	ReceiverID         uint               `json:"receiverID"`
	Txcode             string              `json:"txcode"`
	Sender             *Customer           `json:"sender" gorm:"foreignKey:SenderID"`
	Receiver           *Customer           `json:"receiver" gorm:"foreignKey:ReceiverID"`
	DetailsID          uint                `json:"detailsID"`
	TransactionDetails *TransactionDetails `json:"transactionDetails"`
	SenderAgentID      *string             `json:"senderAgentID"`
	ReceiverAgentID    *string             `json:"receiverAgentID"`
	Status             string              `json:"status"`
}

type TransactionDetails struct {
	gorm.Model
	Txcode           string  `json:"txcode"`
	SentAmount       float64 `json:"sentAmount"`
	SentCurrency     string  `json:"sentCurrency"`
	ReceivedAmount   float64 `json:"receivedAmount"`
	ReceivedCurrency string  `json:"receivedCurrency"`
	Xchange          float64 `json:"xchange"`
	Fees             float64 `json:"fees"`
	PaymentMode      string  `json:"paymentMode"`
	ReceptionMode    string  `json:"receptionMode"`
}

type TransactionDetailsInput struct {
	Txcode           string  `json:"txcode"`
	SentAmount       float64 `json:"sentAmount"`
	SentCurrency     string  `json:"sentCurrency"`
	ReceivedAmount   float64 `json:"receivedAmount"`
	ReceivedCurrency string  `json:"receivedCurrency"`
	Xchange          float64 `json:"xchange"`
	Fees             float64 `json:"fees"`
	PaymentMode      string  `json:"paymentMode"`
	ReceptionMode    string  `json:"receptionMode"`
}

type TransactionInput struct {
	Txcode             string                   `json:"txcode"`
	Sender             *CustomerInput           `json:"sender"`
	Receiver           *CustomerInput           `json:"receiver"`
	TransactionDetails *TransactionDetailsInput `json:"transactionDetails"`
	SenderAgentID      *string                  `json:"senderAgentID"`
	ReceiverAgentID    *string                  `json:"receiverAgentID"`
	Status             string                   `json:"status"`
}
